# Generated by Django 3.2.8 on 2022-03-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='txt_to_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_file', models.FileField(blank=True, upload_to='PDF_to_txt')),
                ('pdf_file', models.FileField(blank=True, upload_to='PDF_to_txt')),
            ],
        ),
    ]
