# Generated by Django 3.2.8 on 2022-03-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='docx_to_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx_file', models.FileField(blank=True, upload_to='DOCX_to_PDF')),
                ('pdf_file', models.FileField(blank=True, upload_to='DOCX_to_PDF')),
            ],
        ),
    ]
